const fs = require('fs');
const html = fs.readFileSync('index.html','utf8');
const failures=[]; const assert=(ok,msg)=>{if(!ok)failures.push(msg)};
const requiredPages=['dashboard','fixtures','umpires','availability','roster','tasks','gameday','finance','payments','reports','notifications','import','rules','coaching','roles','junior','mobile','audit','blueprint','playbook','actionplan'];
for(const page of requiredPages) assert(new RegExp(`\\b${page}:'|\\b${page}:\\s*`).test(html),`Missing page definition: ${page}`);
assert(html.includes('data-action="home"'),'Home breadcrumb is not wired');
assert(html.includes('data-action="current"'),'Current-page breadcrumb is not wired');
assert(html.includes('data-action="season"'),'Season breadcrumb is not wired');
assert(html.includes('b.dataset.go=id'),'Dynamic sidebar navigation is not wired');
assert(html.includes('function openAction('),'Central action dispatcher is missing');
assert(html.includes("document.addEventListener('click'"),'Delegated click handler is missing');
assert(!/href\s*=\s*(['"])#\1/i.test(html),'Placeholder # link found');
for(const match of html.matchAll(/<button\b([^>]*)>/gi)){const attrs=match[1];assert(/data-action=|data-go=/.test(attrs),`Literal button without action wiring: <button${attrs}>`)}
const scriptMatch=html.match(/<script>([\s\S]*)<\/script>/i);assert(!!scriptMatch,'Script block missing');if(scriptMatch){try{new Function(scriptMatch[1])}catch(err){failures.push(`JavaScript syntax error: ${err.message}`)}}
const pageObject=html.match(/const pages=\{([^;]+)\};/s)?.[1]||'';const pageIds=new Set([...pageObject.matchAll(/([A-Za-z][A-Za-z0-9]*):'/g)].map(m=>m[1]));for(const id of requiredPages)assert(pageIds.has(id),`Page missing from pages object: ${id}`);
assert(html.includes("['SETTINGS',['import'"),'Season Import is not positioned under Settings');
assert(html.includes("finance:'Finance'"),'Finance operations page is missing');
assert(html.includes("umpires:'Umpire Register'"),'Umpire Register page is missing');
assert(html.includes('openUmpire'),'Umpire profile click-through is missing');
assert(html.includes('registrations'),'Registration history is missing');
assert(html.includes('coachComments'),'Coach development comments are missing');
assert(html.includes('communications'),'Communication audit trail is missing');
assert(html.includes('Parent / spectator abuse'),'Safeguarding incident category/demo is missing');
assert(html.includes('newIncident')&&html.includes('saveIncident'),'Incident record flow is missing');
assert(html.includes('conflicts'),'Conflict management data is missing');
assert(html.includes('payments:['),'Umpire payment history is missing');
assert(html.includes('approval1')&&html.includes('approval2'),'Two-person payment approval state is missing');
assert(html.includes('Approve as Finance Manager'),'Approval 1 control missing');
assert(html.includes('Approve as Partner'),'Approval 2 control missing');
assert(html.includes('downloadBank'),'Bank CSV export is missing');
assert(html.includes('downloadXero'),'Xero CSV export is missing');
assert(html.includes('downloadCsv'),'CSV download helper is missing');
assert(html.includes('markPaid'),'Mark-paid workflow is missing');
assert(html.includes('Concept exports are mapping-ready demo CSV files only'),'Concept export disclaimer is missing');
assert(html.includes("tasks:'Tasks'"),'Tasks page is missing');
assert(html.includes('newRequest')&&html.includes('sendRequest'),'Request flow is missing');
assert(html.includes('editAvailability')&&html.includes('saveAvailability'),'Availability edit flow is missing');
assert(html.includes('actionAccess'),'Operational action authorisation is missing');
if(failures.length){console.error('ClubRoster static QA failed:');failures.forEach(f=>console.error('- '+f));process.exit(1)}
console.log(`ClubRoster static QA passed: ${requiredPages.length} screens, umpire compliance profiles, dual approval finance and CSV exports.`);
