const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app.js','utf8');
const patch=fs.readFileSync('patch.js','utf8');
const mobile=fs.readFileSync('mobile-app.js','utf8');
const failures=[];const assert=(ok,msg)=>{if(!ok)failures.push(msg)};
const requiredPages=['dashboard','fixtures','umpires','availability','roster','tasks','gameday','finance','payments','reports','notifications','import','rules','coaching','roles','junior','mobile','audit','blueprint','playbook','actionplan'];
assert(html.includes('<script src="app.js"></script>'),'index.html does not load app.js');
assert(html.includes('<script src="patch.js"></script>'),'index.html does not load patch.js');
assert(html.includes('<script src="mobile-app.js"></script>'),'index.html does not load mobile-app.js');
assert(html.includes('data-action="home"'),'Home breadcrumb is not wired');
assert(html.includes('data-action="current"'),'Current-page breadcrumb is not wired');
assert(html.includes('data-action="season"'),'Season breadcrumb is not wired');
assert(!/href\s*=\s*(['"])#\1/i.test(html),'Placeholder # link found');
try{new Function(app)}catch(err){failures.push(`app.js syntax error: ${err.message}`)}
try{new Function(patch)}catch(err){failures.push(`patch.js syntax error: ${err.message}`)}
try{new Function(mobile)}catch(err){failures.push(`mobile-app.js syntax error: ${err.message}`)}
const pageObject=app.match(/const pages=\{([^;]+)\};/s)?.[1]||'';
const pageIds=new Set([...pageObject.matchAll(/([A-Za-z][A-Za-z0-9]*):'/g)].map(m=>m[1]));
for(const id of requiredPages)assert(pageIds.has(id),`Page missing from pages object: ${id}`);
const rendererObject=app.match(/const PAGE_RENDERERS=\{([^;]+)\};/s)?.[1]||'';
const rendererEntries=rendererObject.split(',').map(x=>x.trim());
for(const id of requiredPages)assert(rendererEntries.includes(id)||rendererEntries.some(x=>x.startsWith(id+':')),`Dedicated renderer missing: ${id}`);
assert(!app.includes('simplePage'),'Generic placeholder renderer still exists');
assert(!app.includes('remains connected to the prototype'),'Placeholder copy still exists');
assert(app.includes('b.dataset.go=id'),'Dynamic sidebar navigation is not wired');
assert(app.includes("document.addEventListener('click'"),'Delegated click handler is missing');
assert(app.includes("['SETTINGS',['import'"),'Season Import is not positioned under Settings');
const requiredFunctions=['dashboard','fixturesPage','umpiresPage','availabilityPage','rosterPage','tasksPage','gameDayPage','financePage','paymentsPage','reportsPage','notificationsPage','importPage','rulesPage','coachingPage','rolesPage','juniorPage','mobilePage','auditPage','blueprintPage','playbookPage','actionPlanPage'];
for(const fn of requiredFunctions)assert(new RegExp(`function ${fn}\\(`).test(app),`Page renderer function missing: ${fn}`);
const requiredActions=['fixtureDetail','addFixture','assignUmpire','assignCoach','autoRoster','publish','openUmpire','profileTab','newIncident','saveIncident','coachComment','saveCoachComment','editAvailability','saveAvailability','newRequest','sendRequest','replyTask','resolveTask','gameCheckin','approve1','approve2','downloadBank','downloadXero','markPaid','reviewFee','clearFeeHold','broadcast','sendBroadcast','loadImport','importNext','saveImport','addRule','saveRule','addLevel','saveLevel','previewRole','guardianAck','exportAudit','playbookToggle','planToggle'];
for(const action of requiredActions)assert(app.includes(`a==='${action}'`)||app.includes(`data-action=\"${action}\"`)||app.includes(`'${action}'`),`Required interaction missing: ${action}`);
const requiredData=['Parent / spectator abuse','Club Umpire Registration','Green Bib','Blue Bib','C Badge','Senior Umpire Coach','PAY-R08-001','U11 Development','Gold Coast Netball','Round 8 appointment','Guardian linked','No umpires allocated','Bank CSV','Xero CSV'];
for(const text of requiredData)assert(app.includes(text),`Required dummy data missing: ${text}`);
assert(app.includes('approval1')&&app.includes('approval2'),'Two-person payment approval state is missing');
assert(app.includes('downloadCsv'),'CSV download helper is missing');
assert(app.includes('actionAccess'),'Operational action authorisation is missing');
assert(app.includes('auditEvents'),'Audit trail data is missing');
assert(app.includes('supplyRules'),'Rules & Supply data is missing');
assert(app.includes('levels=['),'Coaching level administration data is missing');
assert(app.includes('permissionRows'),'Roles & Access data is missing');
assert(app.includes('playbookItems'),'Playbook data is missing');
assert(app.includes('actionPlan=['),'Action Plan data is missing');
assert(patch.includes("a==='guardianMessage'"),'Guardian request patch is missing');
assert(patch.includes('playbookToggle'),'Read-only playbook safeguard is missing');
const mobileRequired=['mobilePersonas','mobileAssignments','mobileChats','developmentPlans','PAGE_RENDERERS.mobile=mobileAppPage','Umpire · Mia P','Umpire Coach · Karen W','Umpire Coordinator · Alex C','Game-day Admin · Jordan A','Guardian · Sam J','Accept','Decline game','I have arrived','Game completed','Coaching completed','Game chat','Report incident / issue','Add umpire feedback','My development','My payments','Live court coverage','Close / verify day','Mobile appointment declined','Compliance Task created','Mobile chat sent','Mobile coach feedback saved'];
for(const text of mobileRequired)assert(mobile.includes(text),`Mobile workflow/data missing: ${text}`);
const mobileActions=['persona','tab','accept','decline','confirmDecline','checkin','complete','openChat','gameChat','chatOpen','sendChat','reportIssue','saveIssue','showDevelopment','showPayments','coachFeedback','saveCoachFeedback','liveCoverage','manageFixture','taskOpen','openPerson','closeDay'];
for(const action of mobileActions)assert(mobile.includes(`a==='${action}'`)||mobile.includes(`data-mobile-action=\"${action}\"`),`Mobile action missing: ${action}`);
assert(mobile.includes("tasks.push({id:tasks.length+1,type:'Rostering'"),'Mobile decline does not create rostering Task');
assert(mobile.includes("tasks.push({id:tasks.length+1,type:'Compliance'"),'Mobile issue does not create compliance Task');
assert(mobile.includes("p.coachComments.unshift"),'Mobile coaching feedback does not update umpire record');
assert(mobile.includes("pay.status='Awaiting approval 1'"),'Coach completion does not feed payment readiness');
if(failures.length){console.error('ClubRoster static QA failed:');failures.forEach(f=>console.error('- '+f));process.exit(1)}
console.log(`ClubRoster static QA passed: ${requiredPages.length} substantive screens plus complete mobile-first umpire, coach, coordinator, admin and guardian game-day lifecycles.`);
