const SIMPLE_LABELS={dashboard:'Home',fixtures:'Games & Fixtures',umpires:'Umpires & Coaches',availability:'Availability',roster:'Roster',tasks:'To Do',gameday:'Game Day',finance:'Payments',payments:'Match Fees',reports:'Reports',notifications:'Messages',import:'Season Import',rules:'Basic Roster Rules',coaching:'Coaching Setup',roles:'Who Can Do What',junior:'Juniors & Parents',mobile:'App Preview',audit:'History',blueprint:'System Plan',playbook:'Setup Checklist',actionplan:'Build Plan',netballrules:'Game Rules',duties:'Club Umpire Duties',pathway:'Development Progress',intelligence:'Roster Help'};
Object.entries(SIMPLE_LABELS).forEach(([k,v])=>{if(k in pages)pages[k]=v});
sections.splice(0,sections.length,
 ['EVERYDAY',['dashboard','tasks','roster','fixtures','umpires','availability']],
 ['GAME DAY & PAYMENTS',['gameday','finance','payments','notifications']],
 ['NETBALL SETUP',['netballrules','duties','pathway','intelligence','coaching']],
 ['SETTINGS',['import','rules','junior','roles']],
 ['ADVANCED',['reports','mobile','audit','blueprint','playbook','actionplan']]
);
const SIMPLE_HELP={
 dashboard:['Start here each day','1. Check To Do for anything urgent.','2. Check the Roster for empty games.','3. On Saturday, open Game Day and follow the checklist.'],
 tasks:['To Do','Work from the top down. High priority items should be handled first.','Open an item, fix the problem, then mark it resolved.'],
 roster:['Roster','Red or empty spots need attention.','Use AutoRoster for help, then check the result before you publish.'],
 fixtures:['Games & Fixtures','This is the list of netball games.','Open a game to see the court, teams, umpires and coach.'],
 umpires:['Umpires & Coaches','Open a person to see their registration, development, messages, incidents and payments.','Use restricted incident notes only for genuine safety or compliance matters.'],
 availability:['Availability','This tells you when each umpire or coach can work.','Check changes before building or changing a roster.'],
 gameday:['Game Day','Use this on Saturday to keep the day running smoothly.','Follow the Coordinator Checklist and deal with missing people or incidents as they happen.'],
 finance:['Payments','Payments need two different people to approve them before export.','Do not mark a batch paid until the bank payment has actually been made.'],
 payments:['Match Fees','Check completed games and coaching before approving match fees.','Anything on hold needs to be checked before payment.'],
 notifications:['Messages','Use this for important roster and game-day messages.','Messages that need acknowledgement should stay open until the person confirms them.'],
 netballrules:['Game Rules','Set the minimum umpire level and coaching requirement for each grade.','These rules are used when ClubRoster checks or builds a roster.'],
 duties:['Club Umpire Duties','Shows which club or team must supply an umpire.','Missing duties should be followed up before the roster is published.'],
 pathway:['Development Progress','Shows how each umpire is progressing.','Coach comments and assessments should be clear, respectful and useful.'],
 intelligence:['Roster Help','This screen explains shortages, pairing quality and fairness.','Use it to help make decisions; the coordinator still controls the final roster.'],
 coaching:['Coaching Setup','Set how much coaching each development level should receive.','Use 100% when every eligible game needs coaching.'],
 import:['Season Import','Use this when loading the season fixture file.','Check the preview and warnings before you confirm the import.'],
 rules:['Basic Roster Rules','Set who supplies umpires and other simple roster rules.','Change rules carefully because they affect future rostering.'],
 junior:['Juniors & Parents','Manage guardian links, acknowledgements and junior safety controls.','Keep safeguarding information private and only visible to authorised people.'],
 roles:['Who Can Do What','Controls which parts of ClubRoster each role can use.','Only give people the access they need for their job.']
};
function simpleHelpCard(id){const h=SIMPLE_HELP[id];if(!h)return '';return `<div class="simpleHelp"><div class="simpleHelpIcon">?</div><div><b>${h[0]}</b>${h.slice(1).map(x=>`<div>${x}</div>`).join('')}</div></div>`}
Object.keys(SIMPLE_HELP).forEach(id=>{if(!PAGE_RENDERERS[id])return;const prior=PAGE_RENDERERS[id];PAGE_RENDERERS[id]=function(){return simpleHelpCard(id)+prior()}});
const priorDashboardSimple=PAGE_RENDERERS.dashboard;
PAGE_RENDERERS.dashboard=function(){const urgent=tasks.filter(t=>t.status==='Open'&&t.priority==='High').length,missing=fixtures.filter(f=>!f.ump1||!f.ump2||(!f.coach&&/Development/.test(f.grade))).length;return `<div class="startHere"><div><span>START HERE</span><h2>What should I do now?</h2><p>Work through these four steps. You do not need to use the advanced screens for normal weekly rostering.</p></div><div class="startSteps"><button data-go="tasks"><b>1</b><strong>Check To Do</strong><small>${urgent} urgent item${urgent===1?'':'s'}</small></button><button data-go="roster"><b>2</b><strong>Check Roster</strong><small>${missing} game${missing===1?'':'s'} need attention</small></button><button data-go="gameday"><b>3</b><strong>Run Game Day</strong><small>Checklist, arrivals & issues</small></button><button data-go="finance"><b>4</b><strong>Review Payments</strong><small>Approve only after completion</small></button></div></div>${priorDashboardSimple()}`};
function simpleUxStyles(){if(document.getElementById('simpleUxStyles'))return;const s=document.createElement('style');s.id='simpleUxStyles';s.textContent=`.simpleHelp{display:flex;gap:10px;align-items:flex-start;background:#EEF4FF;border:1px solid #D5E2FA;border-radius:14px;padding:12px 14px;margin:4px 2px 12px;font-size:11px;line-height:1.55}.simpleHelpIcon{width:28px;height:28px;display:grid;place-items:center;border-radius:50%;background:var(--b);color:#fff;font-weight:900;flex:none}.startHere{background:#fff;border-radius:18px;padding:16px;margin:4px 0 12px;box-shadow:var(--shadow)}.startHere span{font-size:9px;font-weight:900;color:var(--b);letter-spacing:.08em}.startHere h2{margin:3px 0}.startHere p{font-size:11px;color:var(--muted)}.startSteps{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.startSteps button{border:1px solid var(--line);background:#fff;border-radius:14px;padding:12px;text-align:left}.startSteps button:hover,.startSteps button:focus{border-color:var(--b);outline:3px solid #2855A622}.startSteps b{display:grid;place-items:center;width:24px;height:24px;border-radius:50%;background:var(--bs);color:var(--b);margin-bottom:8px}.startSteps strong,.startSteps small{display:block}.startSteps small{margin-top:4px;color:var(--muted)}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #2855A644;outline-offset:2px}@media(max-width:760px){.startSteps{grid-template-columns:1fr 1fr}.btn,.quickAction,.phoneNav button{min-height:44px}.appCard{padding:15px}.phoneBody{padding:14px}.simpleHelp{font-size:12px}}`;document.head.appendChild(s)}
simpleUxStyles();
const SIMPLE_CONFIRM={publish:'Publish this roster now? Umpires and coaches may be notified.',markPaid:'Only continue if the bank payment has actually been made. Mark this batch paid?',approve1:'Record the first payment approval?',approve2:'Record the second payment approval?',rollback:'Go back to this older roster version? The current roster will change.',selfAssign:'Take this game now? It will be added to your roster.',signoff:'Sign off the game day? Make sure all critical checks are complete.'};
document.addEventListener('click',e=>{const el=e.target.closest('[data-action],[data-netball-action],[data-open-game-action],[data-checklist-action]');if(!el)return;const action=el.dataset.action||el.dataset.netballAction||el.dataset.openGameAction||el.dataset.checklistAction;const msg=SIMPLE_CONFIRM[action];if(msg&&!window.confirm(msg)){e.preventDefault();e.stopImmediatePropagation()}},true);
function addMobileHelpButton(){if(document.getElementById('mobileSimpleHelp'))return;const b=document.createElement('button');b.id='mobileSimpleHelp';b.className='btn';b.textContent='Help';b.style.cssText='position:fixed;right:14px;bottom:14px;z-index:90;box-shadow:var(--shadow)';b.addEventListener('click',()=>openDrawer('Help',`<h3>Need help?</h3><p>For normal use, follow these steps:</p><ol><li>Check your roster.</li><li>Accept or decline games early.</li><li>Update your availability.</li><li>Use Chat if you need the coordinator.</li><li>Use Report Issue for safety, abuse or other problems.</li></ol><div class="notice">If you are unsure, do not guess. Message the Umpire Coordinator.</div>`));document.body.appendChild(b)}
addMobileHelpButton();
render();
